# We create all Docker images in one workflow to reduce GitHub lfs billing
name: Create and Push Docker Images
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository with lfs
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push API
      uses: docker/build-push-action@v2
      with:
        context: "./api"
        push: true
        tags: ghcr.io/${{ github.actor }}/abacws-api

    - name: Build and push visualiser
      uses: docker/build-push-action@v2
      with:
        context: "./visualiser"
        push: true
        tags: ghcr.io/${{ github.actor }}/abacws-visualiser
